development:
  name: pin-notes
  url: http://dev.notes.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/
  note_repo_path: /root/mindpin_base/note_repo

test:
  name: pin-notes
  url: http://dev.notes.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/
  note_repo_path: /root/mindpin_base/note_repo_test

production:
  name: pin-notes
  url: http://notes.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/
  note_repo_path: /web/2010/note_repo
