development:
  adapter: mysql
  encoding: utf8
  database: user_auth_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql
  encoding: utf8
  database: user_auth_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true


production:
  adapter: mysql
  encoding: utf8
  database: pin-user-auth
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true
