development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: user_auth_development
  pool: 5
  username: root
  password: root
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: user_auth_test
  pool: 5
  username: root
  password: root
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: pin-user-auth
  pool: 5
  username: root
  password: root
  timeout: 5000
