test:
  ttl: 604800
  namespace: user_auth_test
  sessions: false
  debug: false
  servers: localhost:11211

development:
  ttl: 604800
  namespace: user_auth_development
  sessions: false
  debug: false
  servers: localhost:11211

production:
  ttl: 604800
  namespace: user_auth_production
  sessions: false
  debug: false
  servers: localhost:11211