development:
  name: user_auth
  url: http://dev.www.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/
  user_logo_file_path_root: /web/2010/devel_images/
  user_logo_file_url_root: http://dev.img.mindpin.com/

test:
  name: user_auth
  url: http://dev.www.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/
  user_logo_file_path_root: /web/2010/devel_images/
  user_logo_file_url_root: http://dev.img.mindpin.com/

production:
  name: user_auth
  url: http://www.mindpin.com/
  master_url: http://config-manager.mindpin.com
  user_logo_file_path_root: /web/2010/images/
  user_logo_file_url_root: http://img.mindpin.com/
