require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# 与resque相关的 To start a worker, add this to your Rakefile in RAILS_ROOT:
require 'resque/tasks'
