development:
  name: pin-mindmap-editor
  url: http://dev.mindmap-editor.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

test:
  name: pin-mindmap-editor
  url: http://dev.mindmap-editor.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

production:
  name: pin-mindmap-editor
  url: http://mindmap-editor.mindpin.com/
  master_url: http://config-manager.mindpin.com/
