development:
  name: pin-website
  url: http://dev.website.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

test:
  name: pin-website
  url: http://dev.website.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

production:
  name: pin-website
  url: http://website.mindpin.com/
  master_url: http://config-manager.mindpin.com/
