development:
  name: pin-share
  url: http://dev.share.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

test:
  name: pin-share
  url: http://dev.share.mindpin.com/
  master_url: http://dev.config-manager.mindpin.com/

production:
  name: pin-share
  url: http://share.mindpin.com/
  master_url: http://config-manager.mindpin.com
